version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882-8000:7882-8000/udp"
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
    command: --dev --bind 0.0.0.0
    restart: unless-stopped

  egress:
    image: livekit/egress
    container_name: livekit-egress
    depends_on:
      - livekit
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - LIVEKIT_WS_URL=ws://livekit:7880
    volumes:
      - ./recordings:/out
    ports:
      - "8080:8080"
    restart: unless-stopped



