version: '3.8'

services:
  # Redis（LiveKit 和 Egress 都需要）
  redis:
    image: redis:alpine
    container_name: livekit-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # LiveKit 服务器
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880"  # HTTP API
      - "7881:7881"  # WebSocket
      - "7882-8000:7882-8000/udp"  # WebRTC UDP 端口范围
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
    command: --dev --bind 0.0.0.0
    depends_on:
      - redis
    restart: unless-stopped

  # LiveKit Egress 录制服务
  egress:
    image: livekit/egress:latest
    container_name: livekit-egress
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - LIVEKIT_WS_URL=ws://livekit:7880
      - LIVEKIT_HTTP_URL=http://livekit:7880
      - REDIS_ADDRESS=redis:6379
    volumes:
      - ./recordings:/out  # 录制文件存储目录
    ports:
      - "8080:8080"  # Egress API 端口
    depends_on:
      - livekit
      - redis
    restart: unless-stopped

volumes:
  recordings: 